# Pacote
#---------------------------

###
GET /pacotes
Host: localhost:8080

###
POST /pacotes
Host: localhost:8080
Content-Type: application/json

{
		"idUnico": "ABCD1234567",
		"destinatario": "Hermenegildo Silva",
		"endereco": {
			"id": 1
		},
		"status": "pendente"
}

###
POST /pacotes
Host: localhost:8080
Content-Type: application/json

{
		"idUnico": "ABCD1234567",
		"destinatario": "Ana",
		"endereco": {
			"id": 2
		},
		"status": "pendente"
}

###
GET /pacotes/1
Host: localhost:8080

###
GET /pacotes/10
Host: localhost:8080


###
PUT /pacotes/1
Host: localhost:8080
Content-Type: application/json

{
	"status": "em trânsito"
}	 

###
PUT /pacotes/5
Host: localhost:8080
Content-Type: application/json

{
	"status": "teste"
}	 

###
DELETE /pacotes/2
Host: localhost:8080


# Rastreamento
#----------------------------------------------------
###
GET /rastreamentos/2
Host: localhost:8080


# Endereco
#--------------------------------------------------------
###
GET /enderecos/1
Host: localhost:8080

###
POST /enderecos
Host: localhost:8080
Content-Type: application/json

{
	"rua": "Rua das Flores",
	"numero": 123,
	"cidade": "São Paulo",
	"estado": "SP",
	"cep": "12345-678"
}

###
POST /enderecos
Host: localhost:8080
Content-Type: application/json

{
	"rua": "Rua dos Anjos",
	"numero": 15,
	"cidade": "São Paulo",
	"estado": "SP",
	"cep": "4321-876"
}

# Status
#----------------------------------------------------
### Teste para buscar pacotes por status
GET /pacotes/status?status=pendente
Host: localhost:8080
Accept: application/json

# Destinatário
#----------------------------------------------------
### Teste para buscar pacotes por destinatário
GET /pacotes/destinatario?destinatario=Ana
Host: localhost:8080
Accept: application/json